/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AboutRoute } from './routes/about'
import { Route as IndexRoute } from './routes/index'

// Create Virtual Routes

const AboutLazyRoute = AboutRoute
const IndexLazyRoute = IndexRoute

// Create/Update Routes

const AboutRouteWithChildren = AboutRoute._addFileChildren([])
const IndexRouteWithChildren = IndexRoute._addFileChildren([])

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyRoute
      parentRoute: typeof rootRoute
    }
    '/about': {
      preLoaderRoute: typeof AboutLazyRoute
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRouteWithChildren,
  AboutRouteWithChildren,
])

/* prettier-ignore-end */